/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Jefe.Obreros;

import DAOs.JefesDAO;
import DAOs.ObrasDAO;
import DAOs.ObrerosDAO;
import Dominio.Jefes;
import Herramientas.Icono;
import Herramientas.Validadores;
import javax.swing.UIManager;

/**
 *
 * @author 52644
 */
public class PagarObreros extends javax.swing.JFrame {

    // Atributos
    Jefes jefe;
    ObrasDAO ObrasDAO = new ObrasDAO();
    JefesDAO JefesDAO = new JefesDAO();
    ObrerosDAO ObrerosDAO = new ObrerosDAO();
    Validadores valido = new Validadores();
    
    /**
     * Creates new form PagarObreros
     */
    public PagarObreros(Jefes jefe) {
        this.jefe = jefe;
        UIManager.put("OptionPane.yesButtonText", "Aceptar");
        UIManager.put("OptionPane.noButtonText", "Cancelar");
        initComponents();
        new Icono().insertarIcono(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pagar Obreros");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
