/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Acceso;

import DAOs.ClientesDAO;
import DAOs.JefesDAO;
import DAOs.ObrerosDAO;
import Dominio.Clientes;
import Dominio.Jefes;
import Dominio.Obreros;
import GUI.Cliente.PanelCliente;
import GUI.Insercion.InsercionMasiva;
import GUI.Jefe.PanelJefe;
import GUI.Obrero.PanelObrero;
import Herramientas.Icono;
import Herramientas.Insercion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author naely
 */
public class IniciarSesion extends javax.swing.JFrame {

    // Atributos
    private int contador = 0;

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        new Icono().insertarIcono(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        chbVerContrasenia = new javax.swing.JCheckBox();
        lblTipoUsuario = new javax.swing.JLabel();
        cbxTipoUsuario = new javax.swing.JComboBox<>();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        UObraLogo = new javax.swing.JLabel();
        lblTítulo = new javax.swing.JLabel();
        btnRegistrarCuenta = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuHerramientas = new javax.swing.JMenu();
        mniInsercion = new javax.swing.JMenuItem();
        mniInsercionRapida = new javax.swing.JMenuItem();
        mniEliminarBD = new javax.swing.JMenuItem();
        MenuExtras = new javax.swing.JMenu();
        mniAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("UObra Inicio de Sesión");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        chbVerContrasenia.setText("👁");
        chbVerContrasenia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbVerContraseniaStateChanged(evt);
            }
        });

        lblTipoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoUsuario.setText("Tipo de Usuario");

        cbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija uno...", "Obrero", "Jefe", "Cliente" }));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario");

        lblContrasenia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContrasenia.setText("Contraseña");

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar.setText("Acceder");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        UObraLogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UObraLogo.setIcon(new javax.swing.ImageIcon("D:\\Documentos\\Word\\ITSON\\3er-4to Semestre\\4°\\Pruebas de Software\\UObra\\src\\main\\java\\Multimedia\\UObra.png")); // NOI18N

        lblTítulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTítulo.setText("Inicio de Sesión");

        btnRegistrarCuenta.setText("Registro");
        btnRegistrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCuentaActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Nueva cuenta?");

        jLabel2.setText("Ingrese su usuario");

        jLabel3.setText("Ingrese su contraseña");

        MenuHerramientas.setText("Herramientas");

        mniInsercion.setText("Inserción Masiva");
        mniInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInsercionActionPerformed(evt);
            }
        });
        MenuHerramientas.add(mniInsercion);

        mniInsercionRapida.setText("Inserción Rápida");
        mniInsercionRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInsercionRapidaActionPerformed(evt);
            }
        });
        MenuHerramientas.add(mniInsercionRapida);

        mniEliminarBD.setText("Eliminar Base de Datos");
        mniEliminarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarBDActionPerformed(evt);
            }
        });
        MenuHerramientas.add(mniEliminarBD);

        Menu.add(MenuHerramientas);

        MenuExtras.setText("Extras");

        mniAcercaDe.setText("Acerca de");
        mniAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAcercaDeActionPerformed(evt);
            }
        });
        MenuExtras.add(mniAcercaDe);

        Menu.add(MenuExtras);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTítulo)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(169, 169, 169))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblContrasenia)
                                            .addComponent(lblUsuario))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbxTipoUsuario, 0, 226, Short.MAX_VALUE)
                                            .addComponent(txtUsuario)
                                            .addComponent(txtContrasenia))
                                        .addGap(18, 18, 18)
                                        .addComponent(chbVerContrasenia))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(UObraLogo)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(UObraLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTítulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(chbVerContrasenia)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnRegistrarCuenta)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (i == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (this.cbxTipoUsuario.getSelectedItem() == "Elija uno...") {
            JOptionPane.showMessageDialog(null, "Error: Elija un tipo de usuario válido para inicio de sesión.", "¡Error!", JOptionPane.ERROR_MESSAGE);
        } else if (this.cbxTipoUsuario.getSelectedItem() == "Obrero") {
            try {
                ObrerosDAO ObrerosDAO = new ObrerosDAO();
                String usuario = this.txtUsuario.getText().trim();
                String contrasena = new String(this.txtContrasenia.getPassword());
                if (ObrerosDAO.verificarContrasenaUsuario(usuario, contrasena)) {
                    Obreros obrero = ObrerosDAO.consultarObrerosUsuario(usuario);
                    new PanelObrero(obrero).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error: Usuario o contraseña de obrero incorrectas (Intente de nuevo).", "¡Error!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (this.cbxTipoUsuario.getSelectedItem() == "Jefe") {
            try {
                JefesDAO JefesDAO = new JefesDAO();
                String usuario = this.txtUsuario.getText().trim();
                String contrasena = new String(this.txtContrasenia.getPassword());
                if (JefesDAO.verificarContrasenaUsuario(usuario, contrasena)) {
                    Jefes jefe = JefesDAO.consultarJefesUsuario(usuario);
                    new PanelJefe(jefe).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error: Usuario o contraseña de jefe incorrectas (Intente de nuevo).", "¡Error!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (this.cbxTipoUsuario.getSelectedItem() == "Cliente") {
            try {
                ClientesDAO ClientesDAO = new ClientesDAO();
                String usuario = this.txtUsuario.getText().trim();
                String contrasena = new String(this.txtContrasenia.getPassword());
                if (ClientesDAO.verificarContrasenaUsuario(usuario, contrasena)) {
                    Clientes cliente = ClientesDAO.consultarClientesUsuario(usuario);
                    new PanelCliente(cliente).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error: Usuario o contraseña de cliente incorrectas (Intente de nuevo).", "¡Error!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void mniAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAcercaDeActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Autores: \n"
                + " - Brandon Figueroa Ugalde \n"
                + " - Guimel Naely Rubio Morillon \n"
                + "\nProf. María de los Ángeles Germán \n"
                + "Pruebas de Software ITSON "
                + "☺"
                , "Acerca de", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(true);
    }//GEN-LAST:event_mniAcercaDeActionPerformed

    private void mniEliminarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarBDActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "¿Seguro que quiere eliminar la base de datos?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (i == JOptionPane.YES_OPTION) {
            try {
                if (new Insercion().EliminarBaseDeDatos()) {
                    JOptionPane.showMessageDialog(null, "Se eliminó la base de datos correctamente.", "Acción realizada", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "No fue posible eliminar la base de datos.", "¡Error interno!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_mniEliminarBDActionPerformed

    private void mniInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInsercionActionPerformed
        new InsercionMasiva().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniInsercionActionPerformed

    private void btnRegistrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCuentaActionPerformed
        new RegistrarCuenta().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarCuentaActionPerformed

    private void chbVerContraseniaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbVerContraseniaStateChanged
        if (this.chbVerContrasenia.isSelected()) {
            this.txtContrasenia.setEchoChar((char) 0);
        } else {
            this.txtContrasenia.setEchoChar('•');
        }
    }//GEN-LAST:event_chbVerContraseniaStateChanged

    private void mniInsercionRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInsercionRapidaActionPerformed
        if (this.contador == 0) {
            if (new Insercion().InsercionRapida()) {
                this.contador = 1;
                JOptionPane.showMessageDialog(null, "Se realizó la inserción rápida correctamente.", "Acción realizada", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción rápida.", "¡Error interno!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se puede realizar la inserción rápida más de una vez.", "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mniInsercionRapidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuExtras;
    private javax.swing.JMenu MenuHerramientas;
    private javax.swing.JLabel UObraLogo;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegistrarCuenta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxTipoUsuario;
    private javax.swing.JCheckBox chbVerContrasenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mniAcercaDe;
    private javax.swing.JMenuItem mniEliminarBD;
    private javax.swing.JMenuItem mniInsercion;
    private javax.swing.JMenuItem mniInsercionRapida;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
