/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Jefe.Permisos;

import DAOs.JefesDAO;
import DAOs.PermisosDAO;
import Dominio.Jefes;
import Dominio.Permisos;
import Enumeradores.TipoPermiso;
import GUI.Jefe.PanelJefe;
import Herramientas.Encriptador;
import Herramientas.Fecha;
import Herramientas.Icono;
import Herramientas.Validadores;
import java.awt.event.KeyEvent;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author 52644
 */
public class RegistrarPermiso extends javax.swing.JFrame {

    // Atributos
    Jefes jefe;
    Fecha fecha = new Fecha();
    JefesDAO JefesDAO = new JefesDAO();
    PermisosDAO PermisosDAO = new PermisosDAO();
    Validadores valido = new Validadores();
    Encriptador crypt = new Encriptador();

    /**
     * Creates new form RegistrarPermiso
     */
    public RegistrarPermiso(Jefes jefe) {
        this.jefe = jefe;
        UIManager.put("OptionPane.yesButtonText", "Aceptar");
        UIManager.put("OptionPane.noButtonText", "Cancelar");
        initComponents();
        new Icono().insertarIcono(this);
        this.txtFolio.setText("######");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFolio = new javax.swing.JLabel();
        lblTipoPermiso = new javax.swing.JLabel();
        Separador1 = new javax.swing.JSeparator();
        cbxTipo = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        UObraLogoPeque = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblFechaConcesado = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        lblBusqueda = new javax.swing.JLabel();
        fechaConcesion = new com.toedter.calendar.JDateChooser();
        lblFechaConcesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registrar Permiso");
        setResizable(false);

        lblFolio.setText("Folio del permiso....");

        lblTipoPermiso.setText("Elija un tipo de permiso...");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija uno...", "Iniciación", "Finalización" }));
        cbxTipo.setToolTipText("Elija un tipo de permiso");
        cbxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("Registrar Permiso");

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDireccion.setText("Folio:");

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setToolTipText("Registrar permiso");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        UObraLogoPeque.setIcon(new javax.swing.ImageIcon("D:\\Documentos\\Word\\ITSON\\3er-4to Semestre\\4°\\Pruebas de Software\\UObra\\src\\main\\java\\Multimedia\\UObraPeque.png")); // NOI18N

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipo.setText("Tipo:");

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar el registro de permiso");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblFechaConcesado.setText("Ingrese una fecha de concesión...");

        txtFolio.setToolTipText("Max. 6 caracteres");
        txtFolio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFolioFocusLost(evt);
            }
        });
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFolioKeyTyped(evt);
            }
        });

        lblBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBusqueda.setText("Registro:");

        fechaConcesion.setToolTipText("Periodo inicio");

        lblFechaConcesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaConcesion.setText("Fecha concesión:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnRegistrar)
                                .addGap(42, 42, 42)
                                .addComponent(btnCancelar))
                            .addComponent(lblBusqueda)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTipo)
                                    .addComponent(lblFechaConcesion)
                                    .addComponent(lblDireccion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFolio)
                                    .addComponent(lblFechaConcesado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFolio)
                                    .addComponent(lblTipoPermiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fechaConcesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UObraLogoPeque)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo)
                    .addComponent(UObraLogoPeque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFolio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoPermiso)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaConcesado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaConcesion)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnRegistrar)))
                    .addComponent(fechaConcesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            if (this.cbxTipo.getSelectedItem() != "Elija uno...") {
                if (this.fechaConcesion.getCalendar() != null) {
                    if (valido.validarFechas(this.fechaConcesion.getCalendar(), fecha.fechaAhora())) {
                        if (this.txtFolio.getText().length() > 6) {
                            this.txtFolio.setText(this.txtFolio.getText().substring(0, 6));
                        }
                        TipoPermiso tipo;
                        if (this.cbxTipo.getSelectedItem() == "Iniciación") {
                            tipo = TipoPermiso.INICIACION;
                        } else {
                            tipo = TipoPermiso.FINALIZACION;
                        }
                        Permisos permiso = new Permisos(
                                txtFolio.getText(),
                                tipo,
                                fechaConcesion.getCalendar(),
                                this.jefe);
                        Permisos permisoRegistrado = PermisosDAO.registrarPermiso(permiso);
                        if (permisoRegistrado.getId() != null) {
                            try {
                                int i = JOptionPane.showConfirmDialog(null,
                                        "Se realizó exitosamente el registro de permiso con..."
                                        + "\n Folio: " + crypt.decrypt(permisoRegistrado.getFolio())
                                        + "\n Tipo: " + permisoRegistrado.getTipo()
                                        + "\n Fecha de registro: " + fecha.formatoFecha(permisoRegistrado.getFechaRegistro())
                                        + "\n Fecha de concesión: " + fecha.formatoFecha(permisoRegistrado.getFechaConcesion())
                                        + "\n - ID Jefe: " + permisoRegistrado.getJefe().getId()
                                        + "\n - ID: " + permisoRegistrado.getId()
                                        + ". ☺\n"
                                        + "\n ¿Desea registrar otro permiso?", "Registro de permiso exitoso", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, new Icono().obtenerIcono());
                                if (i == JOptionPane.YES_OPTION) {
                                    this.txtFolio.setText("######");
                                    this.cbxTipo.setSelectedItem("Elija uno...");
                                    this.fechaConcesion.setCalendar(null);
                                    this.setVisible(true);
                                } else {
                                    this.dispose();
                                    new PanelJefe(JefesDAO.consultarJefe(this.jefe.getId())).setVisible(true);
                                }
                            } catch (Exception ex) {
                                Logger.getLogger(RegistrarPermiso.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Error interno: Ocurrió un errror al querer registrar el permiso.", "¡Error interno!", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Error: La fecha de concesión no puede ser después que la fecha actual.", "¡Error!", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Error: Ingrese una fecha de concesión.", "¡Error!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error: Seleccione un tipo de permiso válido.", "¡Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            if (e.getCause() != null && e.getCause().getCause() instanceof SQLIntegrityConstraintViolationException) {
                JOptionPane.showMessageDialog(null, "Error: Folio ya existente en la base de datos, ingrese uno diferente.", "¡Error!", JOptionPane.ERROR_MESSAGE);
                this.txtFolio.setText("######");
            } else {
                Logger.getLogger(RegistrarPermiso.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        int i = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas cancelar el registro de permiso? Los datos de registro no se guardarán", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (i == JOptionPane.YES_OPTION) {
            this.dispose();
            new PanelJefe(JefesDAO.consultarJefe(this.jefe.getId())).setVisible(true);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyTyped
        if (txtFolio.getText().length() >= 6) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || !Character.isDigit(c)) {
            evt.consume();
        }
        // Obtener el componente fuente del evento
        JTextField textField = (JTextField) evt.getSource();

        // Verificar si el evento es una operación de pegar
        if (evt.isConsumed() || evt.getKeyChar() == KeyEvent.VK_V && evt.isControlDown()) {
            // Si es una operación de pegar, cancelar el evento
            evt.consume();

            // Vaciar el contenido del campo de texto
            textField.setText("");
        }
    }//GEN-LAST:event_txtFolioKeyTyped

    private void txtFolioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFolioFocusLost
        if (txtFolio.getText().isBlank() || txtFolio.getText().length() < 6) {
            txtFolio.setText("######");
        }
    }//GEN-LAST:event_txtFolioFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separador1;
    private javax.swing.JLabel UObraLogoPeque;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxTipo;
    private com.toedter.calendar.JDateChooser fechaConcesion;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaConcesado;
    private javax.swing.JLabel lblFechaConcesion;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoPermiso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtFolio;
    // End of variables declaration//GEN-END:variables
}
