/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Insercion;

import GUI.Acceso.IniciarSesion;
import Herramientas.Icono;
import Herramientas.Insercion;
import javax.swing.JOptionPane;

/**
 *
 * @author 52644
 */
public class InsercionMasiva extends javax.swing.JFrame {

    // Atributos
    Insercion insercion = new Insercion();

    /**
     * Creates new form InsercionMasiva
     */
    public InsercionMasiva() {
        initComponents();
        new Icono().insertarIcono(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnInsertarClientes = new javax.swing.JButton();
        btnInsertarJefes = new javax.swing.JButton();
        btnInsertarObreros = new javax.swing.JButton();
        btnInsertarObras = new javax.swing.JButton();
        btnInsertarFacturas = new javax.swing.JButton();
        btnInsertarObrasObrero = new javax.swing.JButton();
        btnInsertarPagos = new javax.swing.JButton();
        btnInsertarPermisos = new javax.swing.JButton();
        btnInsertarPlanos = new javax.swing.JButton();
        btnInsertarUbicaciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Inserción Masiva");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Inserción Masiva");

        btnInsertarClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarClientes.setText("Insertar Clientes");
        btnInsertarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarClientesActionPerformed(evt);
            }
        });

        btnInsertarJefes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarJefes.setText("Insertar Jefes");
        btnInsertarJefes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarJefesActionPerformed(evt);
            }
        });

        btnInsertarObreros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarObreros.setText("Insertar Obreros");
        btnInsertarObreros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarObrerosActionPerformed(evt);
            }
        });

        btnInsertarObras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarObras.setText("Insertar Obras");
        btnInsertarObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarObrasActionPerformed(evt);
            }
        });

        btnInsertarFacturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarFacturas.setText("Insertar Facturas");
        btnInsertarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarFacturasActionPerformed(evt);
            }
        });

        btnInsertarObrasObrero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarObrasObrero.setForeground(new java.awt.Color(204, 0, 0));
        btnInsertarObrasObrero.setText("Insertar Obras - Obrero");
        btnInsertarObrasObrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarObrasObreroActionPerformed(evt);
            }
        });

        btnInsertarPagos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarPagos.setForeground(new java.awt.Color(204, 0, 0));
        btnInsertarPagos.setText("Insertar Pagos");
        btnInsertarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPagosActionPerformed(evt);
            }
        });

        btnInsertarPermisos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarPermisos.setText("Insertar Permisos");
        btnInsertarPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPermisosActionPerformed(evt);
            }
        });

        btnInsertarPlanos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarPlanos.setText("Insertar Planos");
        btnInsertarPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPlanosActionPerformed(evt);
            }
        });

        btnInsertarUbicaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarUbicaciones.setText("Insertar Ubicaciones");
        btnInsertarUbicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarUbicacionesActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(183, 183, 183))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertarUbicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsertarObreros, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarJefes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarPermisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnInsertarObras, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnInsertarPlanos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnInsertarPagos)
                            .addComponent(btnInsertarFacturas)
                            .addComponent(btnInsertarObrasObrero, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblTitulo)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInsertarClientes, btnInsertarFacturas, btnInsertarJefes, btnInsertarObras, btnInsertarObrasObrero, btnInsertarObreros, btnInsertarPagos, btnInsertarPermisos, btnInsertarPlanos, btnInsertarUbicaciones});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarClientes)
                    .addComponent(btnInsertarObras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarJefes)
                    .addComponent(btnInsertarPlanos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarObreros)
                    .addComponent(btnInsertarFacturas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarUbicaciones)
                    .addComponent(btnInsertarObrasObrero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarPermisos)
                    .addComponent(btnInsertarPagos))
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarObrasActionPerformed
////        if (insercion.InsercionMasivaObras()) {
////            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de obras correctamente.");
////        } else {
////            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de obras.");
////        }
        insercion.InsercionMasivaObras();
    }//GEN-LAST:event_btnInsertarObrasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        new IniciarSesion().setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInsertarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarClientesActionPerformed
        if (insercion.InsercionMasivaClientes()) {
            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de clientes correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de clientes.");
        }
    }//GEN-LAST:event_btnInsertarClientesActionPerformed

    private void btnInsertarJefesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarJefesActionPerformed
        if (insercion.InsercionMasivaJefes()) {
            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de jefes correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de jefes.");
        }
    }//GEN-LAST:event_btnInsertarJefesActionPerformed

    private void btnInsertarObrerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarObrerosActionPerformed
        if (insercion.InsercionMasivaObreros()) {
            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de obreros correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de obreros.");
        }
    }//GEN-LAST:event_btnInsertarObrerosActionPerformed

    private void btnInsertarUbicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarUbicacionesActionPerformed
////        if (insercion.InsercionMasivaUbicaciones()) {
////            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de ubicaciones correctamente.");
////        } else {
////            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de ubicaciones.");
////        }
        insercion.InsercionMasivaUbicaciones();
    }//GEN-LAST:event_btnInsertarUbicacionesActionPerformed

    private void btnInsertarPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPermisosActionPerformed
////        if (insercion.InsercionMasivaPermisos()) {
////            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de permisos correctamente.");
////        } else {
////            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de permisos.");
////        }
        insercion.InsercionMasivaPermisos();
    }//GEN-LAST:event_btnInsertarPermisosActionPerformed

    private void btnInsertarPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPlanosActionPerformed
////        if (insercion.InsercionMasivaPlanos()) {
////            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de planos correctamente.");
////        } else {
////            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de planos.");
////        }
        insercion.InsercionMasivaPlanos();
    }//GEN-LAST:event_btnInsertarPlanosActionPerformed

    private void btnInsertarObrasObreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarObrasObreroActionPerformed
////        if (insercion.InsercionMasivaObrasObrero()) {
////            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de obras - obrero correctamente.");
////        } else {
////            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de obras - obrero.");
////        }
        insercion.InsercionMasivaObrasObrero();
    }//GEN-LAST:event_btnInsertarObrasObreroActionPerformed

    private void btnInsertarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarFacturasActionPerformed
////        if (insercion.InsercionMasivaFacturas()) {
////            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de facturas correctamente.");
////        } else {
////            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de facturas.");
////        }
        insercion.InsercionMasivaFacturas();
    }//GEN-LAST:event_btnInsertarFacturasActionPerformed

    private void btnInsertarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPagosActionPerformed
////        if (insercion.InsercionMasivaPagos()) {
////            JOptionPane.showMessageDialog(null, "Se realizó la inserción masiva de pagos correctamente.");
////        } else {
////            JOptionPane.showMessageDialog(null, "No se pudo realizar la inserción masiva de pagos.");
////        }
        insercion.InsercionMasivaPagos();
    }//GEN-LAST:event_btnInsertarPagosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertarClientes;
    private javax.swing.JButton btnInsertarFacturas;
    private javax.swing.JButton btnInsertarJefes;
    private javax.swing.JButton btnInsertarObras;
    private javax.swing.JButton btnInsertarObrasObrero;
    private javax.swing.JButton btnInsertarObreros;
    private javax.swing.JButton btnInsertarPagos;
    private javax.swing.JButton btnInsertarPermisos;
    private javax.swing.JButton btnInsertarPlanos;
    private javax.swing.JButton btnInsertarUbicaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
