/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Jefe.Facturas;

import DAOs.FacturasDAO;
import DAOs.JefesDAO;
import Dominio.Facturas;
import Dominio.Jefes;
import Enumeradores.EstadoFactura;
import Enumeradores.MetodoPago;
import GUI.Jefe.PanelJefe;
import Herramientas.Icono;
import Herramientas.Validadores;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author naely
 */
public class PagarFactura extends javax.swing.JFrame {

    // Atributos
    Jefes jefe;
    JefesDAO JefesDAO = new JefesDAO();
    FacturasDAO FacturasDAO = new FacturasDAO();
    Validadores valido = new Validadores();

    /**
     * Creates new form PagoFactura
     */
    public PagarFactura(Jefes jefe) throws Exception {
        this.jefe = jefe;
        UIManager.put("OptionPane.yesButtonText", "Aceptar");
        UIManager.put("OptionPane.noButtonText", "Cancelar");
        initComponents();
        new Icono().insertarIcono(this);
        List<Facturas> facturas = FacturasDAO.consultarFacturasFechaCreada(null, null, EstadoFactura.PENDIENTE, MetodoPago.NO_APLICA, null, this.jefe.getId());
        for (Facturas factura : facturas) {
            this.cbxUnaFactura.addItem(
                    "Factura: " + factura.getDescripcion()
                    + " - Monto: $" + factura.getMonto() + " MXN"
                    + " - ID: " + factura.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        lblFactura = new javax.swing.JLabel();
        lblBusqueda = new javax.swing.JLabel();
        UObraLogoPeque = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        cbxUnaFactura = new javax.swing.JComboBox<>();
        Separador1 = new javax.swing.JSeparator();
        lblElijaFactura = new javax.swing.JLabel();
        lblMetodoPago = new javax.swing.JLabel();
        lblElijaMetodo = new javax.swing.JLabel();
        cbxMetodoPago = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pagar Factura");
        setResizable(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar pago de factura");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblFactura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFactura.setText("Factura:");

        lblBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBusqueda.setText("Registro:");

        UObraLogoPeque.setIcon(new javax.swing.ImageIcon("D:\\Documentos\\Word\\ITSON\\3er-4to Semestre\\4°\\Pruebas de Software\\UObra\\src\\main\\java\\Multimedia\\UObraPeque.png")); // NOI18N

        btnPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.setToolTipText("Pagar factura");
        btnPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("Pagar Factura");

        cbxUnaFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una..." }));
        cbxUnaFactura.setToolTipText("Elija un tipo de permiso");
        cbxUnaFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblElijaFactura.setText("Elija una factura...");

        lblMetodoPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMetodoPago.setText("Método de pago:");

        lblElijaMetodo.setText("Elija un método de pago...");

        cbxMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija uno...", "Efectivo", "Débito", "Crédito" }));
        cbxMetodoPago.setToolTipText("Elija un tipo de permiso");
        cbxMetodoPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(UObraLogoPeque))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblBusqueda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblElijaFactura))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblFactura)
                        .addGap(12, 12, 12)
                        .addComponent(cbxUnaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblElijaMetodo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblMetodoPago)
                        .addGap(12, 12, 12)
                        .addComponent(cbxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnPagar)
                        .addGap(42, 42, 42)
                        .addComponent(btnCancelar)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblTitulo))
                    .addComponent(UObraLogoPeque))
                .addGap(6, 6, 6)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblBusqueda)
                .addGap(6, 6, 6)
                .addComponent(lblElijaFactura)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblFactura))
                    .addComponent(cbxUnaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblElijaMetodo)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblMetodoPago))
                    .addComponent(cbxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagar)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        int i = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cancelar el pago de factura? Los datos de pago no se guardarán", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (i == JOptionPane.YES_OPTION) {
            this.dispose();
            new PanelJefe(JefesDAO.consultarJefe(this.jefe.getId())).setVisible(true);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        if (this.cbxUnaFactura.getSelectedItem() != "Elija una...") {
            if (this.cbxMetodoPago.getSelectedItem() != "Elija uno...") {
                MetodoPago metodo;
                if (cbxMetodoPago.getSelectedItem() == "Débito") {
                    metodo = MetodoPago.DEBITO;
                } else if (cbxMetodoPago.getSelectedItem() == "Crédito") {
                    metodo = MetodoPago.CREDITO;
                } else {
                    metodo = MetodoPago.EFECTIVO;
                }
                // Factura
                String facturaElegida = this.cbxUnaFactura.getSelectedItem().toString();
                String idElegido = facturaElegida.substring(facturaElegida.length() - 3, facturaElegida.length());
                idElegido = valido.obtenerNumeros(idElegido);
                Long id = Long.valueOf(idElegido);
                Facturas factura = FacturasDAO.consultarFactura(id);
                if (factura != null) {
                    FacturasDAO.pagarFactura(id, metodo);
                    int i = 0;
                    try {
                        this.setVisible(false);
                        i = JOptionPane.showConfirmDialog(null,
                                "Se realizó exitosamente el registro de factura con..."
                                + "\n Monto: $ " + factura.getMonto() + " MXN "
                                + "\n Descripción: " + factura.getDescripcion()
                                + "\n - ID: " + factura.getId()
                                + "\n - ID Jefe: " + factura.getJefe().getId()
                                + ". ☺\n"
                                + "\n ¿Desea pagar otra factura?", "Pago de factura exitoso", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, new Icono().obtenerIcono());
                    } catch (Exception ex) {
                        Logger.getLogger(PagarFactura.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (i == JOptionPane.YES_OPTION) {
                        try {
                            this.cbxUnaFactura.removeAllItems();
                            this.cbxUnaFactura.addItem("Elija una...");
                            this.cbxUnaFactura.setSelectedItem("Elija una...");
                            this.cbxMetodoPago.removeAllItems();
                            this.cbxMetodoPago.addItem("Elija uno...");
                            this.cbxMetodoPago.setSelectedItem("Elija uno...");
                            List<Facturas> facturas = FacturasDAO.consultarFacturasFechaCreada(null, null, EstadoFactura.PENDIENTE, MetodoPago.NO_APLICA, null, this.jefe.getId());
                            for (Facturas factura2 : facturas) {
                                this.cbxUnaFactura.addItem(
                                        "Factura: " + factura2.getDescripcion()
                                        + " - Monto: $" + factura2.getMonto() + " MXN"
                                        + " - ID: " + factura2.getId());
                            }
                            this.setVisible(true);
                        } catch (Exception ex) {
                            Logger.getLogger(PagarFactura.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        this.dispose();
                        new PanelJefe(JefesDAO.consultarJefe(this.jefe.getId())).setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Error interno: Ocurrió un errror al querer pagar la factura.", "¡Error interno!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error: Seleccione un método de pago válido.", "¡Error!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error: Seleccione una factura válida.", "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separador1;
    private javax.swing.JLabel UObraLogoPeque;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cbxMetodoPago;
    private javax.swing.JComboBox<String> cbxUnaFactura;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblElijaFactura;
    private javax.swing.JLabel lblElijaMetodo;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
